project:
  type: website
  output-dir: docs

website:
  title: "Angelika Merkel"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: experience.qmd
        text: Experience
      - href: projects.qmd
        text: Projects

    right:
      - icon: github
        href: https://github.com/angemerkel
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: false
    include-in-header: includes/head.html

editor: visual